# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://raomv.github.io/" # the base hostname & protocol for your site, e.g. https://USERNAME.github.io

# Change to your lang - This doesn't translate the theme, it just defines the main language the content is written in.
lang: es-ES

timezone: Europe/Madrid # Change to your timezone - https://kevinnovak.github.io/Time-Zone-Picker/

title: Mis apuntes de Inteligencia Artificial
tagline: 🎓 Cursando una máster en Inteligencia Artificial, aprendiendo sobre visión por computador y aprendizaje automático. 
        🤖 Interesado por la implementación de la IA en la tecnología de defensa, así como los sistemas autónomos. 
description: A Jekyll theme with sidebar for personal website and blog. 
avatar: "assets/img/avatar/avatar.png" # The avatar on sidebar

# Social profiles
email: 
github: raomv
linkedin: raul-marti

# Url for you account: Buy Me A Coffee, Ko-fi, Patreon, etc.
donate:

# License - eg: Copyright, CC BY-NC-SA 4.0, etc.
license: MIT License
licenseUrl: "https://github.com/git/git-scm.com/blob/main/MIT-LICENSE.txt"

# Build settings
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options - https://github.com/jneen/rouge#full-options
    css_class: highlight
    default_lang: python
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

plugins:
  - jekyll-toc
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-minifier

toc:
  min_level: 2
  max_level: 2

jekyll-minifier:
  exclude: "atom.xml"
  uglifier_args:
    harmony: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      toc: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:title
  - scope:
      path: ""
      type: pages
    values:
      layout: "page"

exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json

include:
  - _pages
